# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Zsm's Blog
subtitle:
description:
keywords:
author: wzshiming
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.zsm.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - "CNAME"
  - "robots.txt"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/wzshiming/blog.zsm.io
  branch: gh-pages
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

#################################################################
###################### NexT Configuration #######################
#################################################################
theme_config:
  # ============================================================= #
  # ============= Theme Core Configuration Settings ============= #
  # ============================================================= #

  cache:
    enable: true

  # ============================================================= #
  # ======================= SEO Settings ======================== #
  # ============================================================= #

  seo: true
  index_with_subtitle: true
  exturl: true

  # ============================================================= #
  # ====================== Scheme Settings ====================== #
  # ============================================================= #

  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini

  # ============================================================= #
  # ================= Site Information Settings ================= #
  # ============================================================= #

  footer:
    since: 2019
    icon:
      name: heart
      animated: true
      color: "#808080"
    copyright: wzshiming
    # -------------------------------------------------------------
    powered:
      enable: true
      version: true
    theme:
      enable: true
      version: true

  creative_commons:
    license: by-nc-sa
    sidebar: true
    post: false

  # ============================================================= #
  # ======================= Menu Settings ======================= #
  # ============================================================= #

  menu:
    News: / || bullhorn

    archives: /archives/ || archive

  # Enable / Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: true

  # ============================================================= #
  # ===================== Sidebar Settings ====================== #
  # ============================================================= #

  avatar:
    url: https://avatars0.githubusercontent.com/u/6565744
    rounded: true
    opacity: 1
    rotated: false

  social:
    GitHub: https://github.com/wzshiming || github
    E-Mail: mailto:wzshiming@foxmail.com || envelope
    #Weibo: https://weibo.com/yourname || weibo
    #Google: https://plus.google.com/yourname || google
    #Twitter: https://twitter.com/yourname || twitter
    #FB Page: https://www.facebook.com/yourname || facebook
    #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
    #YouTube: https://youtube.com/yourname || youtube
    #Instagram: https://instagram.com/yourname || instagram
    #Skype: skype:yourname?call|chat || skype
    #RSS: /atom.xml || rss

  social_icons:
    enable: true
    icons_only: true
    transition: true

  # Table of Contents in the Sidebar
  # Front-matter variable (unsupport wrap expand_all).
  toc:
    enable: true
    # Automatically add list number to toc.
    number: true
    # If true, all words will placed on next lines if header width longer then sidebar width.
    wrap: true
    # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
    expand_all: true
    # Maximum heading depth of generated toc.
    max_depth: 6

  sidebar:
    b2t: true
    scrollpercent: true
    onmobile: true

  # ============================================================= #
  # ======================= Post Settings ======================= #
  # ============================================================= #

  # Post wordcount display settings
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: true
    awl: 4
    wpm: 275

  post_edit:
    enable: true
    url: https://github.com/wzshiming/blog.zsm.io/edit/master/source/

  # ============================================================= #
  # ==================== Misc Theme Settings ==================== #
  # ============================================================= #

  mobile_layout_economy: true

  # Remove unnecessary files after hexo generate.
  minify: true

  # `Follow me on GitHub` banner in the top-right corner.
  github_banner:
    enable: true
    permalink: https://github.com/wzshiming
    title: Follow me on GitHub

  # Local Search
  # Dependencies: https://github.com/theme-next/hexo-generator-searchdb
  local_search:
    enable: true
    # If auto, trigger search by changing input.
    # If manual, trigger search by pressing enter key or search button.
    trigger: auto
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # Unescape html strings to the readable one.
    unescape: false
    # Preload the search data when the page loads.
    preload: false

  # Quicklink Support
  # For more information: https://github.com/GoogleChromeLabs/quicklink
  # Front-matter (unsupport home archive).
  quicklink:
    enable: true

    # Home page and archive page can be controlled through home and archive options below.
    # This configuration item is independent of `enable`.
    home: true
    archive: true

    # Default (true) will initialize quicklink after the load event fires.
    delay: true
    # Custom a time in milliseconds by which the browser must execute prefetching.
    timeout: 3000
    # Default (true) will enable fetch() or falls back to XHR.
    priority: true

    # For more flexibility you can add some patterns (RegExp, Function, or Array) to ignores.
    # See: https://github.com/GoogleChromeLabs/quicklink#custom-ignore-patterns
    ignores:

  # Math Formulas Render Support
  math:
    # Default (true) will load mathjax / katex script on demand.
    # That is it only render those page which has `mathjax: true` in Front-matter.
    # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
    per_page: true

    # hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
    mathjax:
      enable: true
      # See: https://mhchem.github.io/MathJax-mhchem/
      mhchem: true

    # hexo-renderer-markdown-it-plus (or hexo-renderer-markdown-it with markdown-it-katex plugin) required for full Katex support.
    katex:
      enable: true
      # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
      copy_tex: true
